[package]
name = "mini-lsm-week-1"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A tutorial for building an LSM tree storage engine in a week."

[dependencies]
anyhow = "1"
# arc-swap = "1"
bytes = "1"
# crossbeam-epoch = "0.9"
crossbeam-skiplist = "0.1"
moka = "0.9"
ouroboros = "0.16"
parking_lot = "0.12"

[dev-dependencies]
tempfile = "3"
