permissions:
  contents: read
on:
  push:
    branches:
      - main

concurrency:
 group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
 cancel-in-progress: true
        
env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RUST_TOOLCHAIN: nightly-2023-12-21
  CARGO_TERM_COLOR: always

name: CI - Check
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ env.RUST_TOOLCHAIN }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy, rustfmt
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@mdbook
      - name: patch for gh-pages build
        run: mv mini-lsm-book/theme/head.hbs._ mini-lsm-book/theme/head.hbs
      - name: check and build
        run: cargo x ci
      - uses: actions/upload-pages-artifact@v3
        with:
          path: mini-lsm-book/book

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
